### ISSUE TITLE
Server side crash with new dev GTNH version 2.0.8.0a

### ISSUE THREAD

**Issue by Zodiack256b** [alkcorp/GTplusplus#577] opened 2019-11-26 02:25 UTC
# Issue Title  
Crash during server startup that points to the GT + + mod

## Context
 How has this issue affected you? What are you trying to accomplish? 
 Providing context helps us come up with a solution that is most useful. 

## Game Environment
 * Modpack Name:  GT New Horizons
 * Version used: 2.0.8.0a
 * Download Link if possible: https://www.dropbox.com/s/tvz5pyl338ki81e/GTNH-1.7.10-2.0.8.0a-dev.zip?dl=0

If not using a modpack:
 * Mod List - Upload to Pastie/Pastebin/etc: 

Also include:
 * Gregtech version: 5.09.33.24
 * IC2 version: 2-2.2.828a-exp
 * Java version: Java 8 231
 * Operating System: Win 10 pro 1909

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [X]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [X]    Multi Player?

[crash-2019-11-25_20.15.19-server.txt](https://github.com/alkcorp/GTplusplus/files/3889758/crash-2019-11-25_20.15.19-server.txt)

**Comment by Zodiack256b** [comment] 2019-11-26 02:26
No error from the GT++ mod then loading client side.

**Comment by draknyte1** [comment] 2019-12-30 19:11
Duplicate of #580

**Closed by draknyte1** 2019-12-30 19:11 UTC
Labels: [DEV] Fixed In Dev., bug, duplicate, major
