### ISSUE TITLE
electric wire cutter cant connect wires

### ISSUE THREAD

**Issue by botn365** [alkcorp/GTplusplus#515] opened 2019-07-21 20:53 UTC
## Current Behavior
the 3x3 grid does not show so you cant connect wires with the electric wire cutter
## Possible Solution
 Not obligatory, but suggest a fix/reason for the bug, 
 or ideas how to implement the addition or change. 

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons? 2.0.7.5
 - [ ]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment] 2019-07-29 17:04
Duplicate of https://github.com/alkcorp/GTplusplus/issues/512.

**Closed by draknyte1** 2019-07-29 17:04 UTC
Labels: duplicate
