### ISSUE TITLE
Large Chicken Egg can't auto insert into Disassembler

### ISSUE THREAD

**Issue by yukieiji** [alkcorp/GTplusplus#601] opened 2020-01-08 16:14 UTC
# Issue Title  
Large Chicken Egg can't insert automatically into the Disassembler[1.7.02.99-pre and 1.7.04.422]

## Current Behavior
Large Chicken Egg can't auto insert into the Disassembler when I haven't put it in I inventory.
Also, Large Scale Auto-assembler(Mode Disassembler) couldn't auto insert it even if it was in the inventory.

## Possible Solution
I think Large Chicken Egg should be able to auto insert into Disassembler.
Even if not, Large Scale Auto-assembler (Mode Disassembler) should be able to auto insert it once in inventory.

## Game Environment
 * Modpack Name:GT:New Horizons
 * Version used:ver2.0.7.5 and ver2.0.8.0Pre4

Also include:
* Gregtech version:5.09.33.16 and 5.09.33.30
* IC2 version:2.2.828a-experimental
* Java version:1.8.0_232
* Operating System:Windows10 and CentOS7

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by botn365** [comment] 2020-01-08 16:19
duplicate of #571

**Closed** 2020-01-08 20:23 UTC
