### ISSUE TITLE
Agricultural Sewer - Fluid Regulator bug

### ISSUE THREAD

**Issue by IdkIdkxd** [alkcorp/GTplusplus#564] opened 2019-10-27 13:47 UTC
# Issue Title  
GT++ [1.7.03.01] craft conflict Agricultural Sewer / Fluid Regulator 

## Expected Behavior
If i wanna craft Agricultural Sewer in MV+ assembler, it will craft Fluid Regulators instead, because they both use MV circuits and MV pumps

## Current Behavior
Well, as i said, it crafts Fluid Regulators

## Possible Solution
Maybe Programmed Circuit for regulators?

## Steps to Reproduce (for bugs)
 1. Try to craft Sewer 3098
 2. Get regulators

## Game Environment
 * Modpack Name:  GTNH
 * Version used: 2.0.7.5

Also include:
 * Gregtech version: ~
 * IC2 version: 2.2.828 ex
 * Java version: 8
 * Operating System: win10

**Comment by draknyte1** [comment] 2020-01-09 12:56
Duplicate of #545

**Closed by draknyte1** 2020-01-09 12:56 UTC
Labels: bug, duplicate, minor
